### ISSUE TITLE
Exception in ConfirmEmailView since upgrading to 0.55

### ISSUE THREAD

**Issue by hleroy** [pennersr/django-allauth#3402]
Since upgrading to v0.55, I have  exceptions in ConfirmEmailView. In the recent commit history, I see 
Commit [c52304f](https://github.com/pennersr/django-allauth/commit/c52304f912e69449c9f1c818dad79b766a9f67c3) which is possibly addressing this issue.

I don't understand the actual impact on the registration workdlow. Is it a priority to patch or wait until v0.56 release ?

```
AttributeError at /accounts/confirm-email/MzAw:1qIRZm:bzdzDhiBmCcTqxvmxoX1yfI68cQCZZfYhgGU_0BpB-I/
'NoneType' object has no attribute 'email_address'

```

```
  File "/usr/local/lib/python3.11/site-packages/allauth/account/views.py", line 301, in get
    ctx = self.get_context_data()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/allauth/account/views.py", line 414, in get_context_data
    "can_confirm": self.object.email_address.can_set_verified(),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^

Exception Type: AttributeError at /accounts/confirm-email/MzAw:1qIRZm:bzdzDhiBmCcTqxvmxoX1yfI68cQCZZfYhgGU_0BpB-I/
Exception Value: 'NoneType' object has no attribute 'email_address'
Raised during: allauth.account.views.ConfirmEmailView
Request information:
USER: AnonymousUser
```

**Comment by hleroy** [comment]
After further testing, the exception is raised when the user clicks a second time on the confirmation link.

**Comment by hleroy** [comment]
> This is fixed in 0.55.2

Thank you very much.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3402
