### ISSUE TITLE
python_2_unicode_compatible Import Errors

### ISSUE THREAD

**Issue by zenjutahi** [pennersr/django-allauth#2466]
ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding'.  This  is happening when using django-allauth with Django version 3.0
 - Please advise

```    from django.utils.encoding import python_2_unicode_compatible
ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding'

**Comment by kiran-capoor94** [comment]
I don't think Django-Allauth supports Django 3.0 yet.

**Comment by kle97** [comment]
I got the same issue.
"django.utils.encoding.python_2_unicode_compatible was removed in Django 3.0. As the release documentation mentions, it was an alias to six.python_2_unicode_compatible. https://docs.djangoproject.com/en/dev/releases/3.0/#removed-private-python-2-compatibility-apis"
https://forum.djangoproject.com/t/python-2-unicode-compatible/715
Please fix this issue.

**Comment by exedar37** [comment]
I was able to get allauth working with Django 3.0 by using the regular six module instead of django's version.  What's the timeline for getting these changes added to allauth?

**Comment by eriktelepovsky** [comment]
+1

**Comment by mattwensing** [comment]
+1

**Comment by ujjwalagrawal17** [comment]
+1

**Comment by rootturk** [comment]
+1

**Comment by pennersr** [comment]
This issue is outdated / no longer relevant.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2466
