### ISSUE TITLE
Apple SSO callback not working with new PyJWT 2.0.0

### ISSUE THREAD

**Issue by winnerNick** [pennersr/django-allauth#2759]
Hi everyone,

Redirection to apple works ok.
When I complete the login process and the callback url is called I get this strange error:

Internal Server Error: /apple/login/callback/finish/

AttributeError at /apple/login/callback/finish/
'str' object has no attribute 'decode'

```
Request Method: GET
Request URL: http://app.myscreenbreak.com/apple/login/callback/finish/?code=cd769c33e10d84e29a4a7fa58706aeea8.0.rzvz.5l-kxFkDaFWt-M-DAVNAog&state=NUB2BztroZto
Django Version: 3.1.5
Python Executable: /usr/local/bin/python
Python Version: 3.8.6
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 77, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 133, in dispatch
    access_token = self.adapter.get_access_token_data(request, app, client)
  File "/usr/local/lib/python3.8/site-packages/allauth/socialaccount/providers/apple/views.py", line 126, in get_access_token_data
    access_token_data = client.get_access_token(code)
  File "/usr/local/lib/python3.8/site-packages/allauth/socialaccount/providers/apple/client.py", line 55, in get_access_token
    client_secret = self.generate_client_secret()
  File "/usr/local/lib/python3.8/site-packages/allauth/socialaccount/providers/apple/client.py", line 44, in generate_client_secret
    client_secret = jwt.encode(

Exception Type: AttributeError at /apple/login/callback/finish/
Exception Value: 'str' object has no attribute 'decode'
```

Any help what is going on here? Thanx!

**Comment by babu-upcomer** [comment]
@winnerNick Seems like PyJWT 2.0.0 upgrade issue. One of your libraries must have installed the latest pyJWT as it's dependency. In my case it was djangorestframework-simplejwt.

**Comment by winnerNick** [comment]
Oh ok, indeed this was the problem.
I had no other library depending on PyJWT and I fixed it by adding **pyjwt[crypto]==1.7.1** in requirements.txt of my project.

PyJWT 2.0.0 released on 22 Dec 2020, so I guess this is a new regression.

Dependecies in setup.py of django-allauth is:
`"pyjwt[crypto] >= 1.7",`

So, I guess this should be now locked on 1.7.x or deny versions above 2.0.0 which are not supported.
I leave the bug open for the package maintainer to decide which option is the best one.

**Comment by LanceMoe** [comment]
#2759
I submitted this PR to fix the problem 8 days ago but seems no one cares...😢

**Comment by gorapidrakesh** [comment]
#2752 This error comes from this method
client_secret = jwt.encode(payload=claims, key=app.certificate, algorithm="ES256", headers=headers).decode("utf-8")
return client_secret

I customized the allauth package by removing decode("utf-8") from jwt and it worked.
Can anyone suggest to me a better way to resolve this error

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2759
