### ISSUE TITLE
Missing change log for 0.19.0 - migration broken with South on Django 1.6.9

### ISSUE THREAD

**Issue by ferrouswheel** [pennersr/django-allauth#804]
Latest is 0.18.0: http://django-allauth.readthedocs.org/en/latest/changelog.html

0.19.0 breaks the syncdb and South's migrate command Django 1.6.9. The migration appears successful apart from the warning "no migrations for the account app":

```
web_1 | Running syncdb and any pending migrations...
web_1 | Syncing...
web_1 | Creating tables ...
web_1 | Creating table auth_permission
web_1 | Creating table auth_group_permissions
web_1 | Creating table auth_group
web_1 | Creating table auth_user_groups
web_1 | Creating table auth_user_user_permissions
web_1 | Creating table auth_user
web_1 | Creating table django_content_type
web_1 | Creating table django_session
web_1 | Creating table django_site
web_1 | Creating table django_admin_log
web_1 | Creating table south_migrationhistory
web_1 | Installing custom SQL ...
web_1 | Installing indexes ...
web_1 | Installed 0 object(s) from 0 fixture(s)
web_1 | Migrating...
web_1 | ? You have no migrations for the 'account' app. You might want some.
web_1 | Running migrations for socialaccount:
web_1 |  - Migrating forwards to 0012_auto__chg_field_socialtoken_token_secret.
web_1 |  > socialaccount:0001_initial
web_1 |  > socialaccount:0002_genericmodels
web_1 |  > socialaccount:0003_auto__add_unique_socialaccount_uid_provider
web_1 |  > socialaccount:0004_add_sites
web_1 |  > socialaccount:0005_set_sites
web_1 |  > socialaccount:0006_auto__del_field_socialapp_site
web_1 |  > socialaccount:0007_auto__add_field_socialapp_client_id
web_1 |  > socialaccount:0008_client_id
web_1 |  > socialaccount:0009_auto__add_field_socialtoken_expires_at
web_1 |  > socialaccount:0010_auto__chg_field_socialtoken_token
web_1 |  > socialaccount:0011_auto__chg_field_socialtoken_token
web_1 |  > socialaccount:0012_auto__chg_field_socialtoken_token_secret
web_1 |  - Loading initial data for socialaccount.
web_1 | Installed 0 object(s) from 0 fixture(s)
web_1 | Running migrations for reversion:
web_1 |  - Migrating forwards to 0008_auto__add_index_revision_date_created.
web_1 |  > reversion:0001_initial
web_1 |  > reversion:0002_auto__add_field_version_type
web_1 |  > reversion:0003_auto__add_field_version_object_id_int
web_1 |  > reversion:0004_populate_object_id_int
web_1 |  > reversion:0005_auto__add_field_revision_manager_slug
web_1 |  > reversion:0006_remove_delete_revisions
web_1 |  > reversion:0007_auto__del_field_version_type
web_1 |  > reversion:0008_auto__add_index_revision_date_created
web_1 |  - Loading initial data for reversion.
web_1 | Installed 0 object(s) from 0 fixture(s)
web_1 |
web_1 | Synced:
web_1 |  > django.contrib.auth
web_1 |  > django.contrib.contenttypes
web_1 |  > django.contrib.sessions
web_1 |  > django.contrib.sites
web_1 |  > django.contrib.messages
web_1 |  > django.contrib.staticfiles
web_1 |  > django.contrib.admin
web_1 |  > django.contrib.admindocs
web_1 |  > allauth
web_1 |  > south
web_1 |  > crispy_forms
web_1 |  > jsonify
web_1 |  > sendfile
web_1 |
web_1 | Migrated:
web_1 |  - allauth.account
web_1 |  - allauth.socialaccount
web_1 |  - reversion
```

However, on login, an error is shown:

```
ProgrammingError at /accounts/login/
relation "account_emailaddress" does not exist
LINE 1: SELECT (1) AS "a" FROM "account_emailaddress" WHERE ("accoun...
```

implying the migration failed.

Reverting django-allauth to 0.18.0 resolves the issue.

**Comment by ferrouswheel** [comment]
If 1.6.9 is no longer supported by django-allauth, then just mentioning as such in the changelog is sufficient to resolve this.

**Comment by cyberjoac** [comment]
Hi, same issue here.
Did you find any fix on this one?

Thanks a lot.

**Comment by dracos** [comment]
The `south_migrations` directory is empty for `allauth.account`, whilst the `migrations` one (for 1.7+) is not. I assume it's a bug and not just dropping of 1.6 support, as other modules have correct South migrations.

In the mean time, you could also potentially add something like `'allauth.account': 'ignore'` to your `SOUTH_MIGRATION_MODULES` as explained at http://south.readthedocs.org/en/latest/settings.html#south-migration-modules so it acted as if no migrations directory was present.

**Comment by miraculixx** [comment]
with South 1.0 and Django >1.6,<1.7 this can be temporarily post installation of django-allauth==0.19.0 fixed using these commands

```
python manage.py schemamigration account --init
python manage.py migrate account
```

**Comment by pennersr** [comment]
This is not something new. The `account` app never had any migrations, as the data models depend on the account settings (specifically, email uniqueness). South duplicates these settings in the migrations, making it impractical to distribute South migrations with the app. Django 1.7 solves this, which is why you'll find migrations for Django 1.7. 

So in fact, nothing changed. You always had to do a `syncdb` for the accounts app, and for Django <1.7 you still have to.

**Comment by ferrouswheel** [comment]
I previously ran `syncdb` for the accounts app.

As it stands the normal Django 1.6/South process of "syncdb" and "migrate --all" doesn't work and it used to. I verified this by going back to 0.18.

By closing this issue I will assume 1.6.9 is no longer supported, and I'm happy with sticking with 0.18 for earlier Django versions.

Happy to provide further details if you need them!

**Comment by pennersr** [comment]
I'll have to look at it at a later time then.  I was assuming syncdb followed by migrate was still working, but apparently is not.

**Comment by ialbert** [comment]
Here is what I think is happening.

The `allauth.socialaccount`  package supports both new style and old style south migrations. It has both a `migrations` and a `south_migrations` directory. A the same time  `allauth.accounts` only has the old style directory with `migrations` the `south_migrations` directory was left empty.

When South starts it uses a heuristics to figure out if the app has new style or old style migrations. Depending on what is listed first in the apps it decides to use the new style `south_migrations` and then tries to use the same for `accounts` as well. But that does not actually exist - hence the error.

**Comment by bcho** [comment]
@miraculixx 

Same approach works on django 1.5.7.


@ialbert 

I don't think that `south` mistaking `migrations` and `south_migrations`, I don't use `socialaccount` in my project but still got the same error as above.

**Comment by ialbert** [comment]
@bcho even so I think it looks at and discovers the wrong directory - running an empty migration will fix the probem:

    python manage.py schemamigration allauth.account --initial

**Comment by pennersr** [comment]
When South investigates what's in the `account.migrations` package, it will run into an `ImportError`, as the logic in `account.migrations.__init__.py` simply raises an `ImportError` in case South is used. This should result replicate the behavior from before the time Django migrations were supported, as back then there simply where no migrations for the `account` app.

According to my tests this fully works now. For those still running into trouble, could you have a go with the latest master? Thanks.

**Comment by ialbert** [comment]
Yes works! It does fix the issue here. 
Thanks.

**Comment by miraculixx** [comment]
Using Django <1.7 and South==1.0, django-allauth>=0.19.1 will (on purpose it appears) raise `ImportError: cannot import name migrations` for the `account` app. To overcome this, add to settings.py:

```
# see http://south.readthedocs.org/en/latest/settings.html#south-migration-modules
SOUTH_MIGRATIONS_MODULES = { 
   'account' : 'ignore',
}
```

Then run `manage.py syncdb --migrate`. Everything should be ok. 

Note if you upgraded from django-allauth>=0.19 and have previously used the `schemamigrate account --init`  hack mentioned above, you need to reset the South migration history for `account`:

```
$ manage.py dbshell
sql> delete from from south_migrationhistory where app_name = 'account'; 
```

**Comment by hanasoo** [comment]
@miraculixx Your comment helped me. Thanks. But I need to change some.

MIGRATION works. Not MIGRATIONS.
```
SOUTH_MIGRATION_MODULES = {
    'account': 'ignore',
}
```

And correct query below
```
sql > delete from south_migrationhistory where app_name = 'account';
```

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/804
